#!/bin/bash

terminal="/bin/bash"
set -e

if (("$#" == 1)); then

	if [[ "$1" = "--help" ]]; then
	echo '
	./getchroot [distributions] <folder>

	Only one option is allowed!

	[distributions]: arch wheezy sid precise raring fedora
		This will download a prepared tar.xz file to ~/.getchroot/ and extract to your given folder
		THERE MIGHT BE SOME ERRORs WHEN EXTRACTING AS USER - tar: dev/dsp: Cannot mknod: Operation not permitted
		However, it should work too.

	EXAMPLES

	:~$ ./getchroot arch mychrootarch
	This will download arch.tar.xz to ~/.getchroot/ if not available and extract it to mychrootarch/
	'
	exit
	fi

elif (("$#" == 2)); then

	if [[ "$1" = "arch" ]]; then
                mkdir -p ~/.getchroot/
                mkdir -p $2
                if [ -f ~/.getchroot/arch.tar.xz ]; then
                        tar -C $2 -xf ~/.getchroot/arch.tar.xz
                else
                        wget -P ~/.getchroot/ http://getchroot.osuv.de/arch.tar.xz
                        tar -C $2 -xf ~/.getchroot/arch.tar.xz
                fi

	elif [[ "$1" = "wheezy" ]]; then
                mkdir -p ~/.getchroot/
                mkdir -p $2
                if [ -f ~/.getchroot/wheezy.tar.xz ]; then
                        tar -C $2 -xf ~/.getchroot/wheezy.tar.xz
                else
                        wget -P ~/.getchroot/ http://getchroot.osuv.de/wheezy.tar.xz
                        tar -C $2 -xf ~/.getchroot/wheezy.tar.xz
                fi

        elif [[ "$1" = "sid" ]]; then
                mkdir -p ~/.getchroot/
                mkdir -p $2
                if [ -f ~/.getchroot/sid.tar.xz ]; then
                        tar -C $2 -xf ~/.getchroot/sid.tar.xz
                else
                        wget -P ~/.getchroot/ http://getchroot.osuv.de/sid.tar.xz
                        tar -C $2 -xf ~/.getchroot/sid.tar.xz
                fi

	elif [[ "$1" = "precise" ]]; then
                mkdir -p ~/.getchroot/
		mkdir -p $2
                if [ -f ~/.getchroot/precise.tar.xz ]; then
                        tar -C $2 -xf ~/.getchroot/precise.tar.xz
                else
                        wget -P ~/.getchroot/ http://getchroot.osuv.de/precise.tar.xz
                        tar -C $2 -xf ~/.getchroot/precise.tar.xz
                fi

        elif [[ "$1" = "raring" ]]; then
                mkdir -p ~/.getchroot/
                mkdir -p $2
                if [ -f ~/.getchroot/raring.tar.xz ]; then
                        tar -C $2 -xf ~/.getchroot/raring.tar.xz
                else
                        wget -P ~/.getchroot/ http://getchroot.osuv.de/raring.tar.xz
                        tar -C $2 -xf ~/.getchroot/raring.tar.xz
                fi

	elif [[ "$1" = "fedora" ]]; then
		mkdir -p ~/.getchroot/
		mkdir -p $2
		if [ -f ~/.getchroot/fedora.tar.xz ]; then
			tar -C $2 -xf ~/.getchroot/fedora.tar.xz
		else
			wget -P ~/.getchroot/ http://getchroot.osuv.de/fedora.tar.xz
			tar -C $2 -xf ~/.getchroot/fedora.tar.xz
		fi
	else
		echo -e "unknown option\n"
	fi
else
	echo -e "getchroot --help\n"
fi
