#!/bin/bash

set -e

function get_proot {

                printf "wget prebuild x86_64 proot binary\n"
                mkdir -p ~/.bin/proot/
                wget -O ~/.bin/proot/proot http://static.proot.me/proot-x86_64
                chmod u+x ~/.bin/proot/proot
                echo "PATH=\$PATH:~/.bin/proot/" >> ~/.bashrc
                echo "export PATH" >> ~/.bashrc
                . ~/.bashrc

}


function print_help {

        echo '
	Usage:
		./getproot
		This will download a precompiled proot binary for x86_64 to ~/.bin/proot/ and add this path to your ~/.bashrc
        '

}

if (("$#" == 1)); then

	if [[ "$1" = "--help" ]]; then
		print_help
		exit

	else
		echo "unknown argument"
		print_help
		exit
	fi

elif (("$#" > 1)); then
        printf "Wrong usage!\n\n"
        print_help
        exit
else
	get_proot
fi
